#!/usr/bin/env bash
# Displays DNS A record info for a domain's subdomains using dig and awk
# shellcheck disable=SC2086

dns_config() {
    local domain="$1"
    local sub="$2"
    local info
    info=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $4, $5}')
    local record_type
    record_type=$(echo "$info" | awk '{print $1}')
    local destination
    destination=$(echo "$info" | awk '{print $2}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    for sub in www lb-01 web-01 web-02; do
        dns_config "$1" "$sub"
    done
elif [ "$#" -eq 2 ]; then
    dns_config "$1" "$2"
fi
